app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/WebController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class WebController extends Controller
{
    public function index()
    {
        return view('page.home');
    }
    public function about()
    {
        return view('page.about');
    }
    public function work()
    {
        return view('page.work');
    }
}

app/View/Components/WebLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class WebLayout extends Component
{
    public $title;
    public function __construct($title)
    {
        $this->title = $title;
    }
    public function render()
    {
        return view('theme.web.main');
    }
}

resources/views/page/about.blade.php
<x-web-layout title="About Me">
    <section id="content">

        <div class="content-wrap pb-0">

            <div class="mw-md container mb-5">
                <h2 class="display-4 fw-light" style="line-height: 1.5;">I am a Freelancer, <span class="gradient-text gradient-horizon">Graphics Designer</span> & <span class="gradient-text gradient-horizon">Frontend Developer</span>, Based in <span class="gradient-text gradient-horizon">Germany</span>. Successful Designer with more than <span class="gradient-text gradient-horizon">10 years</span> of professional experience &amp; with lots of <span class="gradient-text gradient-horizon">Satisfied</span> Customers.</h2>
            </div>

            <div class="clear"></div>

            <div class="section mb-0 p-0" style="background-color: #F4F4F4; overflow: visible;">
                <div class="d-flex justify-content-center position-relative">
                    <div class="parallax min-vh-75" style="background-image: url('demos/freelancer/images/me.jpg'); background-size: cover; background-position: center center;" data-bottom-top="width: 40vw" data-center-top="width: 100vw;">
                        <div class="row align-items-center justify-content-center h-100">
                            <div class="col-auto text-center">
                                <a href="#" class="display-4 fw-bolder text-white d-inline-block mx-4 h-op-08 op-ts"><u>#dribbble</u></a>
                                <a href="#" class="display-4 fw-bolder text-white d-inline-block mx-4 h-op-08 op-ts"><u>#behance</u></a>
                            </div>
                        </div>
                    </div>
                    <div class="shape-divider" data-shape="wave" data-position="bottom"></div>
                </div>
            </div>

            <div class="container mb-5">
                <div class="row col-mb-30 mt-5">
                    <div class="col-md-4">
                        <div class="d-flex align-items-center justify-content-center">
                            <div class="counter counter-xlarge text-dark fw-bolder"><span data-from="1" data-to="15" data-refresh-interval="2" data-speed="600"></span></div>
                            <span>+ Years Of<br>Experience.</span>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="d-flex align-items-center justify-content-center">
                            <div class="counter counter-xlarge text-dark fw-bolder"><span data-from="4" data-to="83" data-refresh-interval="50" data-speed="1500"></span></div>
                            <span>% of Works <br>Completed.</span>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="d-flex align-items-center justify-content-center">
                            <div class="counter counter-xlarge text-dark fw-bolder"><span data-from="5" data-to="100" data-refresh-interval="30" data-speed="1200"></span></div>
                            <span>% Satisfied<br>Customers.</span>
                        </div>
                    </div>
                </div>
                <div class="line line-sm mb-0"></div>
            </div>

            <div class="clear"></div>

            <div class="container mw-md mt-5">
                <h2 class="display-3 fw-bolder text-uppercase">What we Do <span class="gradient-text gradient-horizon">&amp;</span><br> How we Do</h2>
                <div class="row mt-4">
                    <div class="col-md-8 offset-1">
                        <p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque tempora porro hic provident accusamus nam molestias id architecto, temporibus consectetur dolor repellat doloremque dignissimos eum asperiores amet officiis reiciendis libero.</p>
                        <p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque tempora porro hic provident accusamus nam molestias id architecto, temporibus consectetur dolor repellat doloremque dignissimos eum asperiores amet officiis reiciendis libero.</p>
                    </div>
                </div>

                <div class="row align-wide-xxl my-5 text-center">
                    <div class="col-sm-6">
                        <img src="demos/freelancer/images/about/1.jpg" alt="Image" class="img-fluid">
                    </div>
                    <div class="col-sm-6">
                        <img src="demos/freelancer/images/about/2.jpg" alt="Image" class="img-fluid">
                    </div>
                </div>
            </div>

            <div class="section text-center mb-0">
                <div class="mw-xs mx-auto ">
                    <h3 class="display-4 fw-bolder text-uppercase">We Do It for <span class="gradient-text gradient-horizon">Them</span></h3>
                    <p class="mt-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam necessitatibus quaerat, rem delectus</p>

                    <div class="clear"></div>

                    <div class="row justify-content-center align-items-center mt-4 col-mb-30">
                        <div class="col-md-4 col-6 center"><img src="demos/freelancer/images/clients/amazon.svg" alt="Clients"></div>
                        <div class="col-md-4 col-6 center"><img src="demos/freelancer/images/clients/netflix.svg" alt="Clients"></div>
                        <div class="col-md-4 col-6 center"><img src="demos/freelancer/images/clients/google.svg" alt="Clients"></div>
                        <div class="col-md-4 col-6 center"><img src="demos/freelancer/images/clients/paypal.svg" alt="Clients"></div>
                        <div class="col-md-4 col-6 center"><img src="demos/freelancer/images/clients/skype.svg" alt="Clients"></div>
                        <div class="col-md-4 col-6 center"><img src="demos/freelancer/images/clients/ps.svg" alt="Clients"></div>
                        <div class="col-md-4 col-6 center"><img src="demos/freelancer/images/clients/slack.svg" alt="Clients"></div>
                        <div class="col-md-4 col-6 center"><img src="demos/freelancer/images/clients/applemusic.svg" alt="Clients"></div>
                    </div>
                </div>
            </div>
        </div>

    </section>
</x-web-layout>

resources/views/page/work.blade.php
<x-web-layout title="My Work">
    <section id="content">
        <div class="content-wrap py-0">
            <div class="section m-0">
                <div class="container">
                    <div class="row align-items-end justify-content-between mb-5">
                        <div class="col-lg-6 offset-lg-1">
                            <div>
                                <h3 class="fw-bolder display-4 mb-3">Latest Creative <span class="gradient-text gradient-horizon">Works</span> &amp; Selected <span class="gradient-text gradient-horizon">Projects</span></h3>
                                <p class="lead mb-0">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                            </div>
                        </div>
                    </div>
                    <div class="clear"></div>
                    <div class="row justify-content-center col-mb-50 mt-3">
                        <div class="col-lg-6 h-translatey-3 tf-ts">
                            <a href="demo-store.html" class="portfolio-item" target="_blank">
                                <div class="portfolio-image">
                                    <img src="{{asset('semicolon/custom/freelancer/images/works/1.jpg')}}" alt="Portfoio Item">
                                    <div class="bg-overlay">
                                        <div class="bg-overlay-content align-items-start justify-content-start flex-column px-5 py-4">
                                            <h3 class="mb-0 mt-1">Niche Demo Store</h3>
                                            <h5>Media, Icons</h5>
                                        </div>
                                        <div class="bg-overlay-content align-items-start justify-content-end p-4">
                                            <div class="overlay-trigger-icon bg-dark text-white" data-hover-animate="fadeInDownSmall" data-hover-animate-out="fadeOutUpSmall" data-hover-speed="350"><i class="icon-line-link"></i></div>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="col-lg-6 h-translatey-3 tf-ts">
                            <a href="demo-yoga.html" class="portfolio-item" target="_blank">
                                <div class="portfolio-image">
                                    <img src="{{asset('semicolon/custom/freelancer/images/works/2.jpg')}}" alt="Portfoio Item">
                                    <div class="bg-overlay">
                                        <div class="bg-overlay-content align-items-start justify-content-start flex-column px-5 py-4">
                                            <h3 class="mb-0 mt-1">Niche Demo Yoga</h3>
                                            <h5>Media, Icons</h5>
                                        </div>
                                        <div class="bg-overlay-content align-items-start justify-content-end p-4">
                                            <div class="overlay-trigger-icon bg-dark text-white" data-hover-animate="fadeInDownSmall" data-hover-animate-out="fadeOutUpSmall" data-hover-speed="350"><i class="icon-line-link"></i></div>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="col-lg-6 h-translatey-3 tf-ts">
                            <a href="demo-hostel.html" class="portfolio-item" target="_blank">
                                <div class="portfolio-image">
                                    <img src="{{asset('semicolon/custom/freelancer/images/works/3.jpg')}}" alt="Portfoio Item">
                                    <div class="bg-overlay">
                                        <div class="bg-overlay-content align-items-start justify-content-start flex-column px-5 py-4">
                                            <h3 class="mb-0 mt-1">Niche Demo Hostel</h3>
                                            <h5>Media, Icons</h5>
                                        </div>
                                        <div class="bg-overlay-content align-items-start justify-content-end p-4">
                                            <div class="overlay-trigger-icon bg-dark text-white" data-hover-animate="fadeInDownSmall" data-hover-animate-out="fadeOutUpSmall" data-hover-speed="350"><i class="icon-line-link"></i></div>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="col-lg-6 h-translatey-3 tf-ts">
                            <a href="demo-conference.html" class="portfolio-item" target="_blank">
                                <div class="portfolio-image">
                                    <img src="{{asset('semicolon/custom/freelancer/images/works/4.jpg')}}" alt="Portfoio Item">
                                    <div class="bg-overlay">
                                        <div class="bg-overlay-content align-items-start justify-content-start flex-column px-5 py-4">
                                            <h3 class="mb-0 mt-1">Niche Demo Conference</h3>
                                            <h5>Media, Icons</h5>
                                        </div>
                                        <div class="bg-overlay-content align-items-start justify-content-end p-4">
                                            <div class="overlay-trigger-icon bg-dark text-white" data-hover-animate="fadeInDownSmall" data-hover-animate-out="fadeOutUpSmall" data-hover-speed="350"><i class="icon-line-link"></i></div>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</x-web-layout>

resources/views/theme/web/footer.blade.php
<footer id="footer" class="border-0" style="background-color: #C9D6CF;">

    <div class="container">
        <div class="footer-widgets-wrap  m-0">

            <div class="row justify-content-between">

                <div class="col-md-4">
                    <div class="widget">

                        <h3 class="h1 mb-5">Got a Project?<br>Let's Talk!</h3>
                        <span class="text-black-50">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis quisquam aspernatur vero voluptas.</span>
                        <a href="mailto:noreply@canvas.com" class="h4 text-dark mt-5 mb-4 d-block"><u>noreply@canvas.com</u> <i class="icon-line-arrow-right position-relative ms-2" style="top: 3px"></i></a>
                        <div>
                            <a href="http://facebook.com/semicolonweb" class="social-icon si-small si-colored si-facebook" target="_blank">
                                <i class="icon-facebook"></i>
                                <i class="icon-facebook"></i>
                            </a>
                            <a href="http://instagram.com/semicolonweb" class="social-icon si-small si-colored si-instagram" target="_blank">
                                <i class="icon-instagram"></i>
                                <i class="icon-instagram"></i>
                            </a>
                            <a href="http://youtube.com/semicolonweb" class="social-icon si-small si-colored si-youtube" target="_blank">
                                <i class="icon-youtube"></i>
                                <i class="icon-youtube"></i>
                            </a>
                            <a href="#" class="social-icon si-small si-colored si-flattr">
                                <i class="icon-flattr"></i>
                                <i class="icon-flattr"></i>
                            </a>
                        </div>

                    </div>
                </div>

                <div class="col-md-5">
                    <h3 class="h1 mb-5">Estimate your Project?</h3>
                    <div class="form-widget" data-loader="button" data-alert-type="inline">

                        <div class="form-result"></div>

                        <form class="row mb-0" id="landing-enquiry" action="include/form.php" method="post" enctype="multipart/form-data">
                            <div class="form-process"></div>
                            <div class="col-12 form-group mb-4">
                                <label>What is Your Name:</label>
                                <input type="text" name="landing-enquiry-name" id="landing-enquiry-name" class="form-control border-form-control required" value="">
                            </div>
                            <div class="col-12 form-group mb-4">
                                <label>Your Email Address Please:</label>
                                <input type="email" name="landing-enquiry-email" id="landing-enquiry-email" class="form-control border-form-control required" value="">
                            </div>
                            <div class="col-12 form-group mb-4">
                                <label>Tell more about your Project:</label>
                                <textarea name="landing-enquiry-additional-requirements" id="landing-enquiry-additional-requirements" class="form-control border-form-control" cols="10" rows="3"></textarea>
                            </div>
                            <div class="col-12 d-none">
                                <input type="text" id="landing-enquiry-botcheck" name="landing-enquiry-botcheck" value="" />
                            </div>
                            <div class="col-12">
                                <button type="submit" name="landing-enquiry-submit" class="button h-translatey-3 bg-dark rounded-pill"><i class="icon-line-arrow-right m-0"></i></button>
                            </div>

                            <input type="hidden" name="prefix" value="landing-enquiry-">
                        </form>
                    </div>
                </div>

            </div>

        </div>
    </div>

</footer>

resources/views/theme/web/head.blade.php
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="author" content="{{config('app.name')}}" />
	<!-- Stylesheets ============================================= -->
	<link href="https://fonts.googleapis.com/css?family=Heebo:300,400,500,700,900" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" href="{{asset('semicolon/css/bootstrap.css')}}" type="text/css" />
	<link rel="stylesheet" href="{{asset('semicolon/style.css')}}" type="text/css" />
	<link rel="stylesheet" href="{{asset('semicolon/css/dark.css')}}" type="text/css" />
	<link rel="stylesheet" href="{{asset('semicolon/css/font-icons.css')}}" type="text/css" />
	<link rel="stylesheet" href="{{asset('semicolon/css/animate.css')}}" type="text/css" />
	<link rel="stylesheet" href="{{asset('semicolon/css/magnific-popup.css')}}" type="text/css" />
	<link rel="stylesheet" href="{{asset('semicolon/css/custom.css')}}" type="text/css" />
	<!-- Freelancer Demo Specific Stylesheet -->
	<link rel="stylesheet" href="{{asset('semicolon/custom/freelancer/css/fonts.css')}}" type="text/css" />
	<link rel="stylesheet" href="{{asset('semicolon/custom/freelancer/freelancer.css')}}" type="text/css" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<link rel="stylesheet" href="{{asset('semicolon/css/colors.php?color=f7c25e')}}" type="text/css" />
	<!-- Document Title ============================================= -->
	<title>{{config('app.name') . ': ' .$title ?? config('app.name')}}</title>
</head>

resources/views/theme/web/header.blade.php
<header id="header" class="border-bottom-0 no-sticky transparent-header">
    <div id="header-wrap">
        <div class="container">
            <div class="header-row">
                <!-- Logo ============================================= -->
                <div id="logo">
                    <a href="{{route('web.home')}}" class="standard-logo">
                        <img src="" alt="{{config('app.name')}}">
                    </a>
                    <a href="{{route('web.home')}}" class="retina-logo">
                        <img src="" alt="{{config('app.name')}}">
                    </a>
                </div>
                <!-- #logo end -->
                <div class="header-misc">
                    <a href="mailto:noreply@hvlicious.com" class="button button-border rounded-pill">Email Me</a>
                </div>
                <div id="primary-menu-trigger">
                    <svg class="svg-trigger" viewBox="0 0 100 100"><path d="m 30,33 h 40 c 3.722839,0 7.5,3.126468 7.5,8.578427 0,5.451959 -2.727029,8.421573 -7.5,8.421573 h -20"></path><path d="m 30,50 h 40"></path><path d="m 70,67 h -40 c 0,0 -7.5,-0.802118 -7.5,-8.365747 0,-7.563629 7.5,-8.634253 7.5,-8.634253 h 20"></path></svg>
                </div>
                <!-- Primary Navigation ============================================= -->
                <nav class="primary-menu">
                    <ul class="menu-container">
                        <li class="menu-item {{request()->is('about') ? 'current' : ''}}"><a class="menu-link" href="{{route('web.about')}}"><div>About me</div></a></li>
                        <li class="menu-item {{request()->is('works') ? 'current' : ''}}"><a class="menu-link" href="{{route('web.work')}}"><div>Works</div></a></li>
                        <li class="menu-item"><a class="menu-link" href="javascript:;" data-scrollto="#footer" data-easing="easeInOutExpo" data-speed="1250" data-offset="70"><div>Contact</div></a></li>
                    </ul>
                </nav>
                <!-- #primary-menu end -->
            </div>
        </div>
    </div>
</header>

resources/views/theme/web/js.blade.php
<script src="{{asset('semicolon/js/jquery.js')}}"></script>
<script src="{{asset('semicolon/js/plugins.min.js')}}"></script>

<!-- Footer Scripts ============================================= -->
<script src="{{asset('semicolon/js/functions.js')}}"></script>

<script>
    // Owl Carousel Scripts
    jQuery(window).on( 'pluginCarouselReady', function(){
        $('#oc-services').owlCarousel({
            items: 1,
            margin: 30,
            nav: false,
            dots: true,
            smartSpeed: 400,
            responsive:{
                576: { stagePadding: 30, items: 1 },
                768: { stagePadding: 30, items: 2 },
                991: { stagePadding: 150, items: 3 },
                1200: { stagePadding: 150, items: 3}
            },
        });
    });
</script>

resources/views/theme/web/main.blade.php
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
@include('theme.web.head')
<body class="stretched">
	<!-- Document Wrapper ============================================= -->
	<div id="wrapper" class="clearfix">
		<!-- Header ============================================= -->
		@include('theme.web.header')
        <!-- #header end -->
		<!-- Slider ============================================= -->
		@if(request()->is(''))
		@include('theme.web.slider')
		@endif
        <!-- #slider end -->
		<!-- Content ============================================= -->
		{{$slot}}
        <!-- #content end -->
		<!-- Footer ============================================= -->
		@include('theme.web.footer')
        <!-- #footer end -->
	</div>
    <!-- #wrapper end -->
	<!-- Go To Top ============================================= -->
	<div id="gotoTop" class="icon-double-angle-up bg-white text-dark rounded-circle shadow"></div>
	<!-- External JavaScripts ============================================= -->
	@include('theme.web.js')
</body>
</html>

resources/views/theme/web/slider.blade.php
<section id="slider" class="slider-element min-vh-md-100 py-4 include-header" style="background: #FFF url('{{asset('semicolon/custom/freelancer/images/hero-bg.svg')}}') repeat top center; background-size: cover;">
    <div class="slider-inner">
        <div class="vertical-middle slider-element-fade">
            <div class="container text-center py-5">
                <div class="emphasis-title mb-2">
                    <h4 class="text-uppercase ls3 fw-bolder mb-0">I'm a Pakomios Havel</h4>
                    <h1>
                        <span id="oc-images" class="owl-carousel image-carousel carousel-widget" data-items="1" data-margin="0" data-autoplay="3000" data-loop="true" data-nav="false" data-pagi="false" data-animate-in="fadeInUp">
                            <div class="oc-item gradient-text gradient-red-yellow text-uppercase">Developer</div>
                            <div class="oc-item gradient-text gradient-red-yellow text-uppercase">Designer</div>
                        </span>
                    </h1>
                </div>
                <!-- <div class="d-flex align-items-center justify-content-center mb-5">
                    <img src="demos/freelancer/images/face.svg" alt="Face" width="60">
                    <span class="text-uppercase fw-bold ms-3">SemiColonWeb</span>
                </div> -->
                <div class="mx-auto"  style="max-width: 600px">
                    <p class="lead fw-normal text-dark mb-5">Authoritatively expedite backward-compatible e-commerce with cross-media e-commerce. Credibly provide access to world-class action items through resource-leveling resources.</p>
                    <a href="demo-freelancer-works.html" class="button button-dark button-hero h-translatey-3 tf-ts button-reveal overflow-visible bg-dark text-end"><span>View our Works</span><i class="icon-line-arrow-right"></i></a>
                    <a href="#" data-scrollto="#footer" data-easing="easeInOutExpo" data-speed="1250" data-offset="70" class="button button-large button-light text-dark bg-transparent m-0"><i class="icon-line2-arrow-down fw-bold"></i> <u>Contact Me</u></a>
                </div>
            </div>
        </div>
    </div>
</section>